# Generated by Django 3.1.13 on 2022-08-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0011_auto_20220801_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesel', models.IntegerField()),
                ('fastag', models.IntegerField()),
                ('driver_expense', models.IntegerField()),
                ('uncertainty', models.IntegerField()),
                ('miscellaneous', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('booking_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_management.booking')),
            ],
        ),
    ]
