# Generated by Django 3.1.13 on 2022-08-04 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0013_expense_expense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('received_date', models.DateField()),
                ('aknowledgement', models.CharField(choices=[('ok', 'Ok'), ('not ok', 'Not Ok')], max_length=10)),
                ('remarks', models.CharField(max_length=300)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('booking_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_management.booking')),
            ],
        ),
    ]
