# Generated by Django 3.1.13 on 2022-08-05 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0016_auto_20220804_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('transaction_no', models.CharField(blank=True, max_length=220, null=True)),
                ('payment_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('booking_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_management.booking')),
            ],
        ),
    ]
