# Generated by Django 3.1.13 on 2022-08-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0017_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='diesel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='driver_expense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='fastag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='miscellaneous',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='uncertainty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
