# Generated by Django 3.1.13 on 2022-09-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0023_auto_20220812_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='weight_in_tons',
            new_name='weight',
        ),
    ]
