# Generated by Django 3.1.13 on 2022-09-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0024_auto_20220916_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rate',
            new_name='value',
        ),
    ]
