# Generated by Django 3.1.13 on 2022-09-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0025_auto_20220916_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight_in_kg',
            new_name='weight',
        ),
    ]
